import Head from "next/head";

export default function Home() {

	return (
		<>
		<div>
			<Head>
				{/* <title>Create Next App</title>
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/icon?family=Material+Icons"
				/>

				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/icon?family=Material+Icons"
				/> */}
			</Head>

			
				<h1 className="font-body text-4xl">
				 สวัสดีครับ
				</h1>
		

		</div>

<div className="relative mb-5 overflow-x-auto shadow-md rounded-lg">
<table className="w-full text-sm text-left text-gray-500 dark:text-gray-400">
<thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
<tr>
<th scope="col" className="font-sans break-words px-6 py-3">
TOKEN DISTRIBUTION สวัสดีครับ
</th>
<th scope="col" className="px-6 py-3">
VESTING PEROID
</th>
<th scope="col" className="px-6 py-3">
VESTING DATE 
</th>
</tr>
</thead>

 <tbody>
<tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
<th scope="row" className="px-6 py-4 font-medium text-gray-900 dark:text-white">
1% AirDrop
</th>
<td className="px-6 py-4">
10 months
</td>
<td className="px-6 py-4">
11/2022
</td>

</tr>
<tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
<th scope="row" className="px-6 py-4 font-medium text-gray-900 dark:text-white">
8% Marketing
</th>
<td className="px-6 py-4">
20 months
</td>
<td className="px-6 py-4">
09/2022
</td>
</tr>

<tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
<th scope="row" className="px-6 py-4 font-medium text-gray-900 dark:text-white">
10%   Private Sale
</th>
<td className="px-6 py-4">
10 months
</td>
<td className="px-6 py-4">
11/2022
</td>

</tr>
<tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
<th scope="row" className="px-6 py-4 font-medium text-gray-900 dark:text-white">
16% Publice Sale 
</th>
<td className="px-6 py-4">
10 months
</td>
<td className="px-6 py-4">
09/2022
</td>
</tr>

<tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
<th scope="row" className="px-6 py-4 font-medium text-gray-900 dark:text-white">
15% Team
</th>
<td className="px-6 py-4">
30 months
</td>
<td className="px-6 py-4">
11/2022
</td>
</tr>

<tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
<th scope="row" className="px-6 py-4 font-medium text-gray-900 dark:text-white">
4% Advisor
</th>
<td className="px-6 py-4">
4 months
</td>
<td className="px-6 py-4">
02/2023
</td>
</tr>

<tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
<th scope="row" className="px-6 py-4 font-medium text-gray-900 dark:text-white">
10% Staking
</th>
<td className="px-6 py-4">
10 months
</td>
<td className="px-6 py-4">
09/2022
</td>
</tr>

<tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
<th scope="row" className="px-6 py-4 font-medium text-gray-900 dark:text-white">
18% System Reward
</th>
<td className="px-6 py-4">
18 months
</td>
<td className="px-6 py-4">
11/2022
</td>
</tr>

<tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
<th scope="row" className="px-6 py-4 font-medium text-gray-900 dark:text-white">
18% Operating
</th>
<td className="px-6 py-4">
18 months
</td>
<td className="px-6 py-4">
06/2022
</td>

</tr>

</tbody>
</table>
</div>
</>
	);
}
